import 'models/models.dart';

class Global {
  static List<Product> products = [
    Product(
      name: "A.C",
      image: "images/ac.jpg",
      price: 25000,
      quantity: 10,
      counterStart: false,
      outOfStock: false,
    ),
    Product(
      name: "Bag",
      image: "images/bag.jpg",
      price: 900,
      quantity: 10,
      counterStart: false,
      outOfStock: false,
    ),
    Product(
      name: "T-Shirt",
      image: "images/t-shirt.jpg",
      price: 1900,
      quantity: 10,
      counterStart: false,
      outOfStock: false,
    ),
    Product(
      name: "CCTV Camera",
      image: "images/cctv camera.jpg",
      price: 2200,
      quantity: 10,
      counterStart: false,
      outOfStock: false,
    ),
    Product(
      name: "I-Phone",
      image: "images/iphone.jpg",
      price: 70000,
      quantity: 10,
      counterStart: false,
      outOfStock: false,
    ),
    Product(
      name: "Laptop",
      image: "images/laptop.jpg",
      price: 60000,
      quantity: 10,
      counterStart: false,
      outOfStock: false,
    ),
    Product(
      name: "Shoes",
      image: "images/shoes.png",
      price: 2500,
      quantity: 10,
      counterStart: false,
      outOfStock: false,
    ),
    Product(
      name: "Table",
      image: "images/table.jpg",
      price: 2800,
      quantity: 10,
      counterStart: false,
      outOfStock: false,
    ),
    Product(
      name: "T.V.",
      image: "images/tv.jpg",
      price: 25000,
      quantity: 10,
      counterStart: false,
      outOfStock: false,
    ),
    Product(
      name: "Watch",
      image: "images/watch.jpeg",
      price: 1250,
      quantity: 10,
      counterStart: false,
      outOfStock: false,
    ),
  ];
}